### ISSUE TITLE
Significant Slowdown when Upgrading from 0.13.0 to 0.20.0

### ISSUE THREAD

**Issue by veryordinally** [cberner/redb#603] opened 2023-06-03 11:47 UTC
While working on the upgrade from redb 0.13.0 to redb 0.20.0 for `ord` in https://github.com/ordinals/ord/pull/2141, we have encountered a very significant slowdown on our workload. Indexing signet with `--index-sats` takes about 19 minutes on my Mac with 0.13.0 and takes 6 hours and 45 minutes with 0.20.0. Process sys time goes up by a factor of 400. Details of what we changed for the upgrade are in the PR. We also tried with `redb::Durability::Eventual` - still running, but does not seem significantly better.

Before (0.13.0):

```
time target/release/ord --signet --index-sats index
1095.31s user 35.47s system 99% cpu 18:53.03 total
```

After (0.20.0):

```
time target/release/ord --signet --index-sats index
5543.28s user 14072.40s system 80% cpu 6:45:53.23 total
```

These are just our initial findings, will do more investigation. We suspect this is due to the change in https://github.com/cberner/redb/blob/master/CHANGELOG.md#0140---2023-03-26 removing mmap. Any ideas for how to get back to old speed would be much appreciated. As it stands, this would be prohibitively slow to index mainnet - takes good 12 hours currently, and would go up to more than a week if we see the same slowdown.

**Comment by cberner** [comment] 2023-06-03 13:33
Uh oh, well that's not good. Have you tried adjusting `Builder::set_cache_size()`? Try setting that to as much memory as you can afford to give redb.

I'll take a look too. How many blocks do I need to run the indexing for to reproduce the slowdown?

**Comment by cberner** [comment] 2023-06-03 16:51
I tried indexing up to block 150k (kinda low, I know) and got the following:
* 03f6867755c246cf4ea64b9d85134558ce06b9b5 (redb 0.13.0): 1m 17sec
* 113086b27c4587c11af8baa50bf9ed61de378ae7 (redb 0.20.0): 1m 2sec

Have you tried running the indexing on Linux? This might be a MacOS specific issue. Casey & I found that MacOS has very poor performance with sync'ing changes to mmap'ed files, so possibly a similar issue is happening again.

**Comment by veryordinally** [comment] 2023-06-03 18:37
> I tried indexing up to block 150k (kinda low, I know) and got the following:
> 
> * 03f6867755c246cf4ea64b9d85134558ce06b9b5 (redb 0.13.0): 1m 17sec
> * 113086b27c4587c11af8baa50bf9ed61de378ae7 (redb 0.20.0): 1m 2sec
> 
> Have you tried running the indexing on Linux? This might be a MacOS specific issue. Casey & I found that MacOS has very poor performance with sync'ing changes to mmap'ed files, so possibly a similar issue is happening again.

Thanks, will give it a try on Linux. We're just getting a benchmarking server set up for such purposes. So far my tests were on Mac. I am running the tests on signet, and with `--index-sats`, then the slowdown happens after a few minutes once it reaches the first blocks with inscriptions (I believe around block 60k).

**Comment by veryordinally** [comment] 2023-06-03 18:38
> Uh oh, well that's not good. Have you tried adjusting `Builder::set_cache_size()`? Try setting that to as much memory as you can afford to give redb.
> 
> I'll take a look too. How many blocks do I need to run the indexing for to reproduce the slowdown?

Will give this a try on my Mac.

**Comment by veryordinally** [comment] 2023-06-03 18:46
> We also tried with `redb::Durability::Eventual` - still running, but does not seem significantly better.

Here is the result from that run (same Mac, also signet):

```
time target/release/ord --data-dir data-signet-full-eventual --signet --index-sats index
4993.21s user 12776.52s system 99% cpu 4:57:22.76 total
```

**Comment by veryordinally** [comment] 2023-06-03 19:22
@cberner Unfortunately, neither setting 8 GB of cache nor running on Linux seems to make a significant difference - both runs seem to similarly slow (and will likely need a few more hours to finish). Will post numbers here when done.

**Comment by cberner** [comment] 2023-06-03 20:09
I'm able to reproduce it on my Linux desktop using signet. Will dig in shortly!

**Comment by veryordinally** [comment] 2023-06-04 06:22
> > Uh oh, well that's not good. Have you tried adjusting `Builder::set_cache_size()`? Try setting that to as much memory as you can afford to give redb.
> > I'll take a look too. How many blocks do I need to run the indexing for to reproduce the slowdown?
> 
> Will give this a try on my Mac.

Setting an 8GB cache helps somewhat:

```
time target/release/ord --signet --index-sats index
3665.50s user 2513.52s system 99% cpu 1:43:01.65 total
```

This is also with `redb::Durability::Eventual`

Glad to hear you could reproduce it and looking forward to hear what you find!

**Comment by cberner** [comment] 2023-06-05 03:56
Some findings: it looks like this is mainly a perf regression switching from mmap to the pure userspace backend. Which is rather unfortunate, because that was required to make redb safe. Hopefully, I can optimize this to get that performance back.

Findings below:
Indexed up to block 100k on signet:
0.13.0 mmap + 2PC: 16m 21sec
0.13.0 mmap + 1PC+C: 23m 36sec
0.13.0 no-mmap + 2PC: 53m
0.13.0 no-mmap + 1PC+C: 116m 10sec
0.20.0 (implicitly no-mmap + 1PC+C): 115m 32sec

**Comment by veryordinally** [comment] 2023-06-05 20:06
Thanks for the analysis - we suspected that as well. The cache size insight is helpful, but relying on that would make this unusable for a large group of users - people run this on 16GB or 32GB machines. Hope there's other optimization potential. Would also be interested if there's anything in how we use redb that makes our load particularly challenging from a performance perspective? In the Changelog you had stated a maximum slowdown of a factor or 2, but here we see more than 5 - so curious if we're maybe doing anything particularly inefficient?

**Comment by cberner** [comment] 2023-06-06 00:22
Ya, I'm hopeful that implementing a better cache heuristic will allow a similar benefit with a smaller cache size.

I don't think there's anything ord is doing inefficiently, although haven't looked through the code in a while. I think it's just that the ord file size is much bigger than most of the benchmarks that I ran, so I didn't see these cache effects

**Comment by cberner** [comment] 2023-06-07 23:46
I fixed the added overhead from removing `WriteStrategy` in https://github.com/cberner/redb/pull/609

This brings it down to:
* 0.20.0 w/ unlimited (100GB) cache + deferred checksums: 29m 22sec

Next I'm going to work on the caching heuristic, which will hopefully remove the need to use a 100GB cache size

**Comment by raphjaph** [comment] 2023-06-09 12:49
> The cache size insight is helpful, but relying on that would make this unusable for a large group of users - people run this on 16GB or 32GB machines.

Running `ord` with `--index-sats` has always required at least 64GB. I remember buying a new M1 with 32GB and I couldn't index so I had to buy the 64GB version. But if we could get that down to 32GB with some cache magic that would be great!

**Comment by cberner** [comment] 2023-06-09 15:51
https://github.com/cberner/redb/pull/611 should make this much better. I just indexed signet up to 100k with the default 1GB cache size, and it was as fast as setting it to 8GB: 30min. I'm testing indexing mainnet now

**Comment by cberner** [comment] 2023-06-10 21:45
@veryordinally , so I noticed one thing that ord may be doing inefficiently. This `value_cache` is a [HashMap](https://github.com/casey/ord/blob/cadd3b1cce2743fb0c4f9614189eea70ccf2f107/src/index/updater.rs#L653) so the insertion order will be arbitrary. If you can insert them in the same order that they are sorted in redb you'll get better cache hits when updating the file, because values are stored sorted on disk

**Comment by casey** [comment] 2023-06-12 07:36
I created a branch which uses a BTreeMap for both the value cache and the range cache. I didn't benchmark because I'm on a different machine, so it wouldn't be apples to apples, so try it and see if it makes a difference: https://github.com/casey/ord/tree/ordered-insertion

**Comment by veryordinally** [comment] 2023-06-12 15:06
> @veryordinally , so I noticed one thing that ord may be doing inefficiently. This `value_cache` is a [HashMap](https://github.com/casey/ord/blob/cadd3b1cce2743fb0c4f9614189eea70ccf2f107/src/index/updater.rs#L653) so the insertion order will be arbitrary. If you can insert them in the same order that they are sorted in redb you'll get better cache hits when updating the file, because values are stored sorted on disk



> I created a branch which uses a BTreeMap for both the value cache and the range cache. I didn't benchmark because I'm on a different machine, so it wouldn't be apples to apples, so try it and see if it makes a difference: https://github.com/casey/ord/tree/ordered-insertion
> 
> One downside is that unlike a HashMap, BTreeMap storage can't be drained and reused, so this will reallocate the caches when they're committed, which might degrade performance.

Thanks, this is great. I will compare on my machine.

**Comment by cberner** [comment] 2023-06-13 20:46
Ok, redb 0.22.0 should be much faster. I was able to index mainnet up to height 790k using an 8GB cache in 31hrs 42min

**Comment by cberner** [comment] 2023-06-14 19:23
I just ran with redb 0.13.0 for comparison and it took 20hr 47min, so it looks like this is now within the expected performance delta! I'm going to close this, but feel free to re-open if you still encounter a regression

**Closed by cberner** 2023-06-14 19:23 UTC
